# Generated by Django 5.1 on 2024-10-15 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('men_id', models.AutoField(primary_key=True, serialize=False)),
                ('men_name', models.CharField(max_length=100)),
                ('men_email', models.EmailField(max_length=254, unique=True)),
                ('men_subject', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lec_id', models.AutoField(primary_key=True, serialize=False)),
                ('lec_name', models.CharField(max_length=100)),
                ('lec_email', models.EmailField(max_length=254, unique=True)),
                ('lec_subject', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.course')),
            ],
        ),
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('ses_id', models.AutoField(primary_key=True, serialize=False)),
                ('ses_date', models.DateField()),
                ('ses_subject', models.CharField(max_length=100)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.student')),
            ],
        ),
    ]
