# Generated by Django 5.1 on 2024-10-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMIM_peer', '0002_remove_note_lecturer_remove_mentoringsession_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('men_id', models.AutoField(primary_key=True, serialize=False)),
                ('men_name', models.CharField(max_length=100)),
                ('men_email', models.EmailField(max_length=254, unique=True)),
                ('men_subject', models.CharField(max_length=100)),
                ('men_username', models.CharField(max_length=50)),
                ('men_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lec_id', models.AutoField(primary_key=True, serialize=False)),
                ('lec_name', models.CharField(max_length=100)),
                ('lec_email', models.EmailField(max_length=254, unique=True)),
                ('lec_subject', models.CharField(max_length=100)),
                ('lec_username', models.CharField(max_length=50)),
                ('lec_pass', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_name', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.course')),
                ('lec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_email', models.EmailField(max_length=254, unique=True)),
                ('stud_username', models.CharField(max_length=50)),
                ('stud_pass', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.course')),
            ],
        ),
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('ses_id', models.AutoField(primary_key=True, serialize=False)),
                ('ses_date', models.DateField()),
                ('ses_subject', models.CharField(max_length=100)),
                ('men_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.mentor')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.student')),
            ],
        ),
    ]
