# Generated by Django 5.1 on 2024-10-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMIM_peer', '0005_lecturer_mentor_note_student_mentoringsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lec_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='men_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='ses_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
