# Generated by Django 5.1 on 2024-10-21 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMIM_peer', '0006_alter_lecturer_lec_id_alter_mentor_men_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
