# Generated by Django 5.1 on 2024-10-21 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMIM_peer', '0007_note_note_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringsession',
            name='ses_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
