# Generated by Django 5.1 on 2024-10-22 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMIM_peer', '0008_mentoringsession_ses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringsession',
            name='stud_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KPMIM_peer.student'),
        ),
    ]
